#!/bin/bash

# Update the package list and upgrade the packages
sudo apt-get update
sudo apt-get upgrade -y

# Install Nginx
sudo apt-get install nginx -y

# Create a custom 404 page file
sudo bash -c 'cat > /var/www/html/404.html << EOF
<!DOCTYPE html>
<html>
<head>
	<title>404 Not Found</title>
</head>
<body>
	<h1>404 Not Found</h1>
	<p>Ceci n'est pas une page</p>
</body>
</html>
EOF'

# Configure Nginx to use the custom error page
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF'

# Test the configuration and reload Nginx
sudo nginx -t && sudo systemctl reload nginx
